POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "Test",
  	"author": "John Doe",
  	"url": "http://example.com",
  	"likes": 0
}

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/63b6a65edbaa3c2e01fb714c

###
DELETE http://localhost:3003/api/blogs/63b6a65edbaa3c2e01fb714c

###
PUT http://localhost:3003/api/blogs/63d3b145a9f63f3793bd04d2
Content-Type: application/json

{
	"title": "Test",
  	"author": "John Doe",
  	"url": "http://example.com",
  	"likes": 123
}