POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "Test",
  	"author": "John Doe",
  	"url": "http://example.com",
  	"likes": 0
}

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/

###
DELETE http://localhost:3003/api/blogs/63d0e84c665e26805f03c639

###
PUT http://localhost:3003/api/blogs/63d3b145a9f63f3793bd04d2
Content-Type: application/json

{
	"title": "Test",
  	"author": "John Doe",
  	"url": "http://example.com",
  	"likes": 123
}